import numpy as np
from matplotlib.pyplot import (plot, show, subplot, figure,
                               scatter, colorbar, hist, legend,
                               xlabel, ylabel, title)
from numpy import (random, linspace)

x = linspace(0, 2 * np.pi)
figure(1)
subplot(2, 1, 1)
plot(x, np.sin(x))
subplot(2, 1, 2)
plot(x, np.sin(2 * x))
figure(2)
x = linspace(0, 2 * np.pi, 50)
y = np.sin(x)
scatter(x, y)
figure(3)
x = random.rand(1000)
y = random.rand(1000)
size = random.rand(1000) * 50
color = random.rand(1000)
scatter(x, y, size, color)
colorbar()
figure(4)
x = random.randn(1000)
hist(x, 5)
figure(5)
x = linspace(0, 2 * np.pi, 50)
plot(x, np.sin(x), label='Sin(x)')
plot(x, np.cos(x), label='Cos(x)')
legend()
xlabel('Rads')
ylabel('Amplitude')
title('Sin and Cos Waves')
show()
